plugins {
    alias(libs.plugins.luximmo.android.application)
    alias(libs.plugins.luximmo.android.compose)
    alias(libs.plugins.luximmo.android.hilt)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.example.luximmo"

    defaultConfig {
        applicationId = "com.example.luximmo"
        versionCode = 1
        versionName = "0.0.1"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
        signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    buildFeatures {
        buildConfig = true
    }
    testOptions.unitTests.isIncludeAndroidResources = true
}

dependencies {
    implementation(project(":feature:listings"))
    implementation(project(":core:ui"))
    implementation(project(":core:domain"))
    implementation(project(":core:data"))
    implementation(project(":core:database"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.hilt.navigation.compose)

    // Installs the bundled Baseline Profile at runtime so ART can pre-compile hot code paths.
    implementation(libs.androidx.profileinstaller)
    // Consumes the profile generated by the :benchmark module's BaselineProfileGenerator.
    "baselineProfile"(project(":benchmark"))

    //testing
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}
